### ISSUE TITLE
Try Sierra as an Standalone project. 

### ISSUE THREAD

**Issue by joniko** [sierra-library/sierra#13]
I'll love to play around sierra before link it to my project. Something like to have on your demo page.

Thanks!

**Comment by maraisr** [comment]
Hey mate - you sure can.. You can easily download the `dist/sierra.min.css` file and use that to try. Alternatively you can use [CodePen](http://codepen.io/) to test with.

**Comment by joniko** [comment]
I was talking about something like your demo page but with the SCSS. I want to customize it before use it on my project.

**Comment by JoanClaret** [comment]
Hi, what you can do, is:

- [Download](https://github.com/sierra-library/sierra/archive/master.zip)  the source files.
- [Download](https://github.com/sierra-library/sierra-library.github.io/blob/master/index.html) the demo index.html file to the source files folder
- Change the src route for the CSS file in the index.htm to dev/sierra.css

You should be ready to change variables, compile (with gulp) and see the results.

**Comment by joniko** [comment]
Thanks! :)
