### ISSUE TITLE
Weird classes for container sizes

### ISSUE THREAD

**Issue by peterbrinck** [sierra-library/sierra#14]
I find it very weird with the classes for `container` sizes

There's three classes for the container:
`.container`
`.container-small`
`.container-xs` 

<br>

I think it should be consistent with the naming, so it's easier to remember and use.
The current 3 classes is confusing, in the way that two of them have the same "size", small. One is even smaller than small - Does it make sense?

I recommend using these classes instead, for easy use and consistent naming:
`.container`
`.container-medium` - equivalent to `.container-small`
`.container-small` - equivalent to `.container-xs`

---

Also, I find it weird that there isn't SCSS/SASS variables for all the container sizes.

**Comment by JoanClaret** [comment]
Agree, so true!
Do you want me to change it, or do you prefer to open a PR?

**Comment by peterbrinck** [comment]
I'm just going open a PR :+1:

**Comment by JoanClaret** [comment]
Great!
https://github.com/sierra-library/sierra/pull/15
