### ISSUE TITLE
Transition on Buttons

### ISSUE THREAD

**Issue by devswert** [sierra-library/sierra#18]
Hi!
When you do a transition on button hover, this listen only the `background-color`, if you add (or replace background property) `opacity` can see that the transition it's more clean.

**Comment by maraisr** [comment]
HI @devswert thank you for the insight, this whole mechanism has been rectified in Version 2, in fact, we don't affect the opacity of the button at all, we simply transition the background colour, to a slightly darker variation. So you can use the button on any background, and it won't look different than the rest.

**Comment by JoanClaret** [comment]
Fixed to animate the opacity. I've added animation also in the forms (focus state).
Thank you!

https://github.com/sierra-library/sierra/commit/69fb0893e15009d2bff604f3e6f71eafdae5ecac
