### ISSUE TITLE
Add FontAwesome as Dependency

### ISSUE THREAD

**Issue by CinKon** [sierra-library/sierra#24]
Hi,

Fontawesome is missing in your repository. Could you add it by default?

**Comment by JoanClaret** [comment]
Actually, we are working on remove FontAwesome as a dependency.

It would be amazing if installing Font Awesome weren't a requirement to using this library, don't you think?

**Comment by CinKon** [comment]
Of course, since you only need FA for the checkbox-arrows. If you replace them with svg or something, it would be better, of course :)

**Comment by JoanClaret** [comment]
yeah, thats the idea. 
Thank you anyway for suggest enhancements!
:thumbsup:
