### ISSUE TITLE
Doesn't compile with libsass

### ISSUE THREAD

**Issue by anlutro** [sierra-library/sierra#25]
Trying to compile with sassc (node-sass should be the same) yields:

```
Error: Import directives may not be used within control directives or mixins.
        on line 28 of sierra/src/_sierra.scss
>>   @import 'scss/flexboxgrid';
   --^
```

`@import` inside `@if` statements are apparently not really supported by sass, they just happen to work with the ruby compiler.

**Comment by JoanClaret** [comment]
oh, ok, thanks.
We'll find another solution to select the grid system.

**Comment by musicmunky** [comment]
is there a workaround for this currently?  I got the same error and can't generate the sierra.css file.

**Comment by JoanClaret** [comment]
Since we can't use `@if` or `@mixin` with `@import`, the only solution i can find will be comment or uncomment the import lines:

```  
//@import 'scss/flexboxgrid';
@import 'scss/bootstrapgrid';
 ```

Does anyone have a better idea?

**Comment by musicmunky** [comment]
Yeah that's basically what I did - just commented out the if-statement and did the normal bootstrapgrid import.  I'll see if I can come up with a better solution.

**Comment by brianbower** [comment]
Why not just include the library commented out? That is how it's commonly done. I recommend deleting `$flexboxgrid: false` and adding the imports in `_sierra.scss` as such:
```scss
//@import 'scss/flexboxgrid';
@import 'scss/bootstrapgrid';
```
No need to use uncommon/strange SCSS syntax.
