### ISSUE TITLE
Add some form of dropdown?

### ISSUE THREAD

**Issue by Ehesp** [sierra-library/sierra#26]
Awesome lib, looks great.

Only thing I'm not keen on is the fact that "dropdowns", for example on the menus are the default browser select options. Anything that can be done/made?

**Comment by JoanClaret** [comment]
Hi @Ehesp! 
Default selects are useful to display just a simple dropdown. They are cross browser, and all mobile devices displays them with their own style.
The problem styling selects,  is that we need javascript, so i think is not a good idea to develop it.
