### ISSUE TITLE
Add Hello World

### ISSUE THREAD

**Issue by josephspurrier** [sierra-library/sierra#27]
I'm not familiar with SCSS so it's going to take me a little while to figure out how it works. A hello world application would be good for new users to help adoption.

**Comment by alajarvela** [comment]
It's just a SCSS-framework, you're supposed to compile it into CSS. It's not an application so I don't see this relevant.

**Comment by josephspurrier** [comment]
I was still pretty confused on what the project was so I had to look through the source. I suggest updating the README with a quickstart that has more information.
