### ISSUE TITLE
Textarea horizontal resize overflows parent

### ISSUE THREAD

**Issue by Rominou34** [sierra-library/sierra#29]
Hi, while browsing the home page of your library, I tried resizing a textarea and it actually reacted weirdly

So basically you can resize it both vertically and horizontally, and while vertical resizing is acting normally, horizontal resizing doesn't work as I thought it would: when you release the mouse, the textarea remains the same size ( so it's not overflowing its parent, good ), but the symbol in the bottom right of the textarea on which you click to resize actually stays where you left it

![Example](http://i.imgur.com/c0Hp74r.jpg)
I tried puttin `max-width: 100%` on the `.textarea textarea` and it actually behaved like I think it should

*Note:* It's actually my first ever contribution outside my personal projects, sorry if I did it the wrong way.

**Comment by brianbower** [comment]
It looks like the solution is to add the class `textarea` to the textarea element, rather than the wrapping div.

**Comment by JoanClaret** [comment]
Class `textarea` was on a wrapper div to add posibility to include HTML (for example user image) overlaping the textarea.
I did't thought about that. 
Now is fixed, thanks for sharing this issue!
