### ISSUE TITLE
Is Sierra abandoned project?

### ISSUE THREAD

**Issue by drnasin** [sierra-library/sierra#41]
hello there, just wanted to ask if there will be any updates to the library or the project is dead?

**Comment by elboletaire** [comment]
This project is not dead and has been updated during the last months (with less activity during the summer, which is pretty normal).

If you have any suggestion / bug report or whatever you can open an issue or even a PR.

**Comment by drnasin** [comment]
Great to hear! Meaning I can use it in my new project. I based my question on the last change date on Sierra page (05/05/2016)

**Comment by JoanClaret** [comment]
i get your point. 
the idea is refactor the code using BEM or SUIT naming convention and release a new major version, but we don't know yet when will be released.

any help will be much appreciated.
