### ISSUE TITLE
_variables.scss

### ISSUE THREAD

**Issue by Hemant07** [sierra-library/sierra#43]
Line 55 of testscss/src/_variables.scss: Invalid CSS after " 'primary'": expected ")", was ": ..."

**Comment by JoanClaret** [comment]
Did you modify this file? it should compile correctly.

**Comment by elboletaire** [comment]
What sass parser are you using?

**Comment by Hemant07** [comment]
i am using Scout

**Comment by JoanClaret** [comment]
the file compiles correctly. must be something in your Scout config.
