### ISSUE TITLE
how configuration in webpack?

### ISSUE THREAD

**Issue by AdhanIsCuber** [sierra-library/sierra#44]
I including in app.jsx by `import "sierral-ibrary"`
but getting error :
```
ERROR in ./node_modules/sierra-library/dist/sierra.min.css
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
```

**Comment by JoanClaret** [comment]
Looks like there is a misspelling error:

`import "sierral-ibrary"`

Try with:

`import "sierra-library"`

**Comment by AdhanIsCuber** [comment]
Sure,
I miss it

Thanks
