### ISSUE TITLE
Define global variables as default

### ISSUE THREAD

**Issue by sztal** [sierra-library/sierra#45]
Hi,

I thinks that it would be great if you included global variables with `!default` flags so they can be easily overwritter in custom `.scss` files.

And thanks for awesome work!

**Comment by maraisr** [comment]
Thank you @sztal - we will look at this soon.

**Comment by JoanClaret** [comment]
We are working on a new version, that will include `!default` parameter in all configuration variables.
https://github.com/sierra-library/sierra/blob/v3/src/_variables.scss
it's not ready for production yet, but we hope to be ready in a near future.
Thanks for your recommendation @sztal !
