### ISSUE TITLE
v3.0 Button text invisible for some colours

### ISSUE THREAD

**Issue by timpur** [sierra-library/sierra#54]
If you look at the demo page, Outlined and Transparent buttons have an issue if you click (focus) and move your mouse off the button element the text becomes invisible. Something to do with hover i guess ?

![image](https://user-images.githubusercontent.com/7701482/47284323-a9c88600-d632-11e8-8468-d9e790a6068f.png)

![image](https://user-images.githubusercontent.com/7701482/47284252-70901600-d632-11e8-8432-77fc9d90cf9d.png)

**Comment by JoanClaret** [comment]
awwww, this is because of the uncontrolled "active" state.
i'll fixit asap.

Thanks for your comments!

**Comment by JoanClaret** [comment]
Fixed.

Cheers

**Comment by timpur** [comment]
:)
