### ISSUE TITLE
header nav scrollbar

### ISSUE THREAD

**Issue by Coding-Kiwi** [sierra-library/sierra#65]
`.header-nav` should have `overflow-x: auto` instead of `scroll`
the first thing one sees when entering the http://sierra-library.github.io website is an ugly scrollbar :D

![image](https://user-images.githubusercontent.com/5007641/51025435-52301b80-158c-11e9-8535-806e973c0da3.png)

**Comment by JoanClaret** [comment]
haha, nice catch for windows users ;)
fixed, thanks for reporting!
