### ISSUE TITLE
Latest Version, Input has display block not inline-block

### ISSUE THREAD

**Issue by timpur** [sierra-library/sierra#67]
![image](https://user-images.githubusercontent.com/7701482/53478310-9dfe3c00-3aca-11e9-9a25-3e0f8ce34b97.png)

This means there is no difference with or without `fullWidth`.

This might also be an issue for textarea? Or is this intended ?

**Comment by JoanClaret** [comment]
The idea is to get all the space the container have, but you're right, then there is no difference with the `fullWidth`. Maybe we should think about it.
We could add a variable (`$size-form`) to set a default width for non `fullWidth` items.

**Comment by JoanClaret** [comment]
Fixed.
thank you!
