### ISSUE TITLE
Please do the same for Foundation 6, pretty please.

### ISSUE THREAD

**Issue by moondawg69** [sierra-library/sierra#7]
This is such a great base. Foundation NEEDS it.

**Comment by pngnlib** [comment]
Foundation is a great and very powerful framework and this is a very tiny library.
We have different objectives
: )

**Comment by moondawg69** [comment]
I meant the grid only….

Jeremy Timms
Director
Torpedo Juice Ltd.

+++++++++++++++++++++++

26 Longmeads
Tunbridge Wells
Kent
TN3 0AX

T. 0845 520 5250
M. 0759 0553213

E. jez@torpedojuice.co.uk
W. http://www.torpedojuice.co.uk

Torpedo Juice Ltd. is registered in England and Wales Company Number: 05511817 

Private & Confidential
----------------------
This email is private and confidential. It must not be disclosed to, copied or used by anyone other than the addressee. If you receive this email in error, please notify our email administrator at postmaster@torpedojuice.co.uk and delete the email.

Virus Warning
-------------
Although this email and any attachment are believed to be free from viruses which might affect any system into which they are received or opened, it is the responsibility of the recipient to ensure that they are virus free. No responsibility is accepted by the sender for any loss or damage arising in any way from their receipt, opening or use.

**Comment by pngnlib** [comment]
ah, ok, sorry for the misunderstanding. 
ok, i put it on the queue of things to do.
i'll tell you something!

**Comment by moondawg69** [comment]
Thank you very much. 

Sent by Jez, currently out of the office.

**Comment by JoanClaret** [comment]
V3 has been released. i guess this issue is deprecated.
cheers.
